language: php
php:
  - 7.4

before_script: |
  git clone https://github.com/junegunn/vader.vim.git
  git clone https://github.com/tpope/vim-projectionist.git
  git clone https://github.com/noahfrederick/vim-composer.git
  composer create-project laravel/laravel:^8.0 test/fixtures/laravel-8
script: |
  vim -Nu test/fixtures/init.vim -c 'Vader! test/*' > /dev/null
